/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id: "us-east-2:9c26e16d-8b15-48f0-ba18-95ddc01841af",
  aws_cognito_region: "us-east-2",
  aws_user_pools_id: "us-east-1_sv0cuJc0p",
  aws_user_pools_web_client_id: "7t4nk7ke5hedn8jpplmo5t0ipd",
  oauth: {},
  aws_user_files_s3_bucket: "amplify-projectrepoprovas-dev-232906-deployment",
  aws_user_files_s3_bucket_region: "us-east-1",
};

export default awsmobile;

// AWS.config.region = 'us-east-2'; // Region
// AWS.config.credentials = new AWS.CognitoIdentityCredentials({
//     IdentityPoolId: 'us-east-2:9c26e16d-8b15-48f0-ba18-95ddc01841af',
// });
